matrix:
    include:
        -   os: linux
            dist: trusty
            language: python
            python: 2.7
            before_install:
                - pip install -r requirements.txt
            install:
                - python setup.py install
        -   os: osx
            install:
                - python setup.py install --user
script:
    - bash test/test.sh
after_install:
    - coveralls
