matrix:
    include:
        -   os: linux
            dist: trusty
            language: python
            python: 2.7
            before_install:
                - pip install -r requirements.txt
        -   os: osx
install:
    - python setup.py install
script:
    - bash test/test.sh
after_install:
    - coveralls
