matrix:
    include:
        -   os: linux
            dist: trusty
            sudo: required
            language: python
            python: 2.7
        -   os: osx
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - test/test.sh
